### ISSUE TITLE
Did this project die or closed-source ?

### ISSUE THREAD

**Issue by TriMoon** [inbasic/open-two-factor-authenticator#15]
Accoarding to [Official site info](https://add0n.com/two-factor-authenticator.html#log-container):
  - latest version: `0.1.4`
  - published: `10/5/2016`

, yet this [repo only contains](https://github.com/inbasic/open-two-factor-authenticator/commits/) v0.1.2 as last

**Comment by Grossdm** [comment]
Thanks for opening this issue - the lure of a syncing, FOSS 2FA/OTP app had grabbed my interest.
My opinion is that anything related to the  http://add0n.com site is dodgy.

Recently I looked at a Firefox addon and found that it was based on that website. The license was listed as Mozilla, and that "home page" had a link labeled "Fork me on GitHub".

It didn't work. I wasted some time liking at another FF addon by the same dev, and it did have a working link to GitHub.

He had only one public repo, despite the various addons he had on "http://add0n.com".

I have recently started using [andOTP](https://github.com/andOTP/andOTP), which I found on F-Droid.
I haven't used it long enough to recommend it, but it does look like it's under active development.

**Comment by inbasic** [comment]
@Grossdm add0n.com is a free hosting and at least 20 develoeprs are hosting their addons in this website!

Anyway, the project at current state is dead maily because

1. Chrome removed the support for packaged apps
2. Firefox does not support storage API

So basically there is no point to mainting the project.
